kind: Service
apiVersion: v1
metadata:
  name: DemoSEDB
  labels:
    app: DemoSEDB
spec:
  type: ClusterIP
  selector:
    app: DemoSEDB
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: DemoSEDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DemoSEDB
  template:
    metadata:
      labels:
        app: DemoSEDB
        version: v1
    spec:
      containers:
      - name: DemoSEDB
        image: DemoSEDB
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
